services:
  proofread:
    build: .
    restart: unless-stopped
    ports:
      - "8052:3001"
    environment:
      - LLM_BASE_URL=http://p-cloud.local:8002
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - homepage.group=Apps
      - homepage.name=Proofread
      - homepage.description=Correcteur et traducteur de texte assist√© par IA
      - homepage.href=http://p-cloud.local:8052
      - homepage.icon=https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons@main/svg/libretranslate.svg
